import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export const handler = async (event, context) => {
  // Only allow POST requests
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: 'Method Not Allowed',
    };
  }

  try {
    const data = JSON.parse(event.body);
    const { fullName, workEmail, company, interest, requirement } = data;

    // Validate input
    if (!fullName || !workEmail || !company || !interest || !requirement) {
      return {
        statusCode: 400,
        body: JSON.stringify({ message: 'Missing required fields' })
      };
    }

    // Send email via Resend
    const { data: emailData, error } = await resend.emails.send({
      from: 'Blaiselogic Website <onboarding@resend.dev>', // Resend testing domain
      to: [process.env.NOTIFICATION_EMAIL || 'hello@blaiselogic.com'], // Uses an env var for the destination email
      reply_to: workEmail,
      subject: `New Website Inquiry from ${fullName} at ${company}`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
          <div style="background-color: #4E8DFE; padding: 24px; text-align: center;">
            <h2 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">New Website Inquiry</h2>
          </div>
          
          <div style="padding: 32px 24px;">
            <p style="color: #64748b; font-size: 15px; margin-top: 0; line-height: 1.6;">You have received a new message from the Blaiselogic website contact form.</p>
            
            <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 28px;">
              <h3 style="margin-top: 0; margin-bottom: 16px; color: #0b131e; font-size: 16px; border-bottom: 1px solid #e2e8f0; padding-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px;">Contact Details</h3>
              <p style="margin: 0 0 12px; color: #0b131e; font-size: 15px;"><strong style="color: #64748b; display: inline-block; width: 85px;">Name:</strong> ${fullName}</p>
              <p style="margin: 0 0 12px; color: #0b131e; font-size: 15px;"><strong style="color: #64748b; display: inline-block; width: 85px;">Email:</strong> <a href="mailto:${workEmail}" style="color: #4E8DFE; text-decoration: none;">${workEmail}</a></p>
              <p style="margin: 0; color: #0b131e; font-size: 15px;"><strong style="color: #64748b; display: inline-block; width: 85px;">Company:</strong> ${company}</p>
            </div>
            
            <div style="margin-bottom: 28px;">
              <h3 style="margin-top: 0; margin-bottom: 12px; color: #0b131e; font-size: 16px; text-transform: uppercase; letter-spacing: 0.5px;">Primary Interest</h3>
              <span style="color: #4e8dfe; background-color: rgba(78,141,254,0.1); padding: 8px 14px; border-radius: 6px; display: inline-block; font-weight: 600; font-size: 14px;">${interest}</span>
            </div>
            
            <div>
              <h3 style="margin-top: 0; margin-bottom: 12px; color: #0b131e; font-size: 16px; text-transform: uppercase; letter-spacing: 0.5px;">Requirement Details</h3>
              <div style="background-color: #f8fafc; border-left: 4px solid #4E8DFE; padding: 18px; color: #334155; line-height: 1.6; font-size: 15px; border-radius: 0 8px 8px 0;">
                ${requirement.replace(/\n/g, '<br/>') || '<em>No specific requirements provided.</em>'}
              </div>
            </div>
          </div>
          
          <div style="background-color: #f1f5f9; padding: 18px; text-align: center; color: #64748b; font-size: 13px; border-top: 1px solid #e2e8f0;">
            This email was automatically generated by the Blaiselogic website.
          </div>
        </div>
      `
    });

    if (error) {
      console.error('Resend Error:', error);
      return {
        statusCode: 500,
        body: JSON.stringify({ message: 'Error sending email', error: error.message })
      };
    }

    return {
      statusCode: 200,
      body: JSON.stringify({ message: 'Email sent successfully', id: emailData?.id })
    };

  } catch (error) {
    console.error('Server Error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ message: 'Internal Server Error' })
    };
  }
};
